#!/usr/bin/env python3

import numpy as np
from numpy.linalg import inv

"""
Author: R. Klasen, roklasen@uni-mainz.de or r.klasen@gsi.de

Uses multiple overlap matrices and the ideal detector matrices to compute alignment matrices for each sensor.
Each combiner is responsible for a single module.

Steps:

WAIT UPDATE

Okay so now I can create the overlap matrices like they are in the geometry (with alignment) from the ideal matrices plus the misalignment for the overlap.
perfect, I only need to do the three steps I did to arrive here backwards! no base transforming etc, just do the three steps backwards.

END UPDATE

REMEMBER. The overlap matrices come from the Reco Points and are thusly already in PANDA global!

- gather perfect 0->x matrices
- substract (inverse multiply actually) perfect matrices to combined 0->x matrices
- remainder is misalignment AS GIVEN IN PANDA GLOBAL SYSTEM
- base transform each misalignment matrix to system of respective sensor
- save to dict, return to master
"""


class alignmentMatrixCombiner:

    def __init__(self, modulePath):
        self.modulePath = modulePath
        self.alignmentMatrices = {}
        self.overlapMatrices = None
        self.overlapInfos = None
        self.idealDetectorMatrices = None
        self.externalMatrices = None

    def setOverlapMatrices(self, matrices):
        self.overlapMatrices = matrices

    def setIdealDetectorMatrices(self, matrices):
        self.idealDetectorMatrices = matrices

    def setExternallyMEasuredMatrices(self, matrices):
        self.externalMatrices = matrices

    def setOverlapInfos(self, infos):
        # should only contain the overlap infos relevant to THIS combiner, not all the overlaps!
        self.overlapInfos = infos
        tempDict = {}
        # add small overlap to each overlap info, we'll need that info later
        for info in self.overlapInfos:

            # check if modulePath from constructor and overlapInfo match
            if self.modulePath != self.overlapInfos[info]['pathModule']:
                print(f"ERROR! Module path mis match: {self.modulePath} and {self.overlapInfos[info]['pathModule']}")

            smallOverlap = self.getSmallOverlap(info)
            self.overlapInfos[info]['smallOverlap'] = smallOverlap
            tempDict[smallOverlap] = self.overlapInfos[info]

        # and sort by new small overlap. that's okay, the real overlapID is still a field of the dict
        self.overlapInfos = tempDict

    def getDigit(self, number, n):
        return int(number) // 10**n % 10

    def getSmallOverlap(self, overlap):
        return str(self.getDigit(overlap, 0))

    def getMatrixP1ToP2(self, path1, path2):
        # matrix from pnd global to sen1
        m1 = np.array(self.idealDetectorMatrices[path1]).reshape(4, 4)
        # matrix from pnd global to sen2
        m2 = np.array(self.idealDetectorMatrices[path2]).reshape(4, 4)
        # matrix from sen1 to sen2
        return np.linalg.inv(m1)@m2

    def getMatrixP1ToP2fromMatrixDict(self, path1, path2, mat):
        # matrix from pnd global to sen1
        m1 = np.array(mat[path1]).reshape(4, 4)
        # matrix from pnd global to sen2
        m2 = np.array(mat[path2]).reshape(4, 4)
        # matrix from sen1 to sen2
        return np.linalg.inv(m1)@m2

    def getOverlapMatrixWithMisalignment(self, overlapInfo):

        # this is atm the smallOverlap, which is wrong
        p1 = overlapInfo['path1']
        p2 = overlapInfo['path2']
        m1to2ideal = self.getMatrixP1ToP2(p1, p2)
        # this needs the complete overlapID
        m1to2corr = self.overlapMatrices[overlapInfo['smallOverlap']]

        return m1to2corr@m1to2ideal

    def combineMatrices(self):
        # checks here
        if self.overlapMatrices is None or self.idealDetectorMatrices is None or self.overlapInfos is None:
            print(f'ERROR! Please set overlaps, overlap matrices and ideal detector matrices first!')
            return

        if self.externalMatrices is None:
            print(f'ERROR! Please set the exernally measured matrices for sensor 0 and 1 for module {self.modulePath}!')
            return

        # create all intermediate matrices here
        m0 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['0'])
        m1 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['1'])
        m2 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['2'])
        m3 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['3'])
        m4 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['4'])
        m5 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['5'])
        m6 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['6'])
        m7 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['7'])
        m8 = self.getOverlapMatrixWithMisalignment(self.overlapInfos['8'])

        # these two matrices are measured externally, e.g. by microscope
        # for now, they are generated by a different function
        # m0t1 =

        m1t2 = m4 @ inv(m5)
        m1t3 = m4 @ inv(m1)
        m1t4a = m4 @ inv(m5) @ m6 @ inv(m2)
        m1t4b = m4 @ inv(m1) @ m7 @ inv(m8)

        m1t5 = m0
        m1t6 = m4 @ inv(m1) @ m3
        m1t7 = m4 @ inv(m1) @ m7
        m1t8 = m4
        m1t9a = m4 @ inv(m5) @ m6
        m1t9b = m4 @ inv(m1) @ m7 @ inv(m8) @ m2

        print(f'm1t2: {m1t2}')
        print(f'm1t3: {m1t3}')
        print(f'm1t4a: {m1t4a}')
        print(f'm1t4b: {m1t4b}')
        print(f'm1t5: {m1t5}')
        print(f'm1t6: {m1t6}')
        print(f'm1t7: {m1t7}')
        print(f'm1t8: {m1t8}')
        print(f'm1t9a: {m1t9a}')
        print(f'm1t9b: {m1t9b}')

        # # remove ideal here

        # # remainder is here

        # transform here

        # save to dict sensorID : alignment matrix here

    def getAlignmentMatrices(self):
        return self.alignmentMatrices

    pass
